apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAAvonHnqVjbFl7y1vT7DRqBnlfXEgt4JwEOKygzrhxgIqMzGuI9Poovx5oKKmRBdUBSbqjFrHrmuyxrEVsUIcULsK2c53LCP9lU9KYjAbqzndEA22LCNupgnzsWATvBeNpOzP3mH/vTbeNeK1lcU93PW/rPKBedftLmRqUo4XQQVFuNzm2QxhYjEXhVnpW5Z7oAYSEGaJyAFLPgvWPCdwmGqz/aOnA+hEFDjBUkFrpL7gw3+WYaPqa70CV7OsOcI8N5nXo4DBO5GVIPGMhBlhpOEaqaFQpE6hOFWG0oTHCsFTUkkmuQ1ziVtO0mRR7youHjsX37Vt4AemSEaiu2Vt9tY0RCGILJa8KeeHTMDMLpjDdK8f2zxVxwbFz8MEpfZPK7zryxp/7eCWZ1gjD/HpiyYFulSif6BV8AlkWRSSIG0bpyPMll1y/viL0oWoKZFSjjW5UdnAxXhEbGTDpW3lq2iDKvSqNYMGklpdBxEkrUsRXKp/gBsY824PTU6IC0pjCQt2tgaDOkttdz5jhjNJn/75aNJ/Ql5kK0h2aU/MrSf5uybKrbyAfBJvP81QEF4TlQEj9b/MjXu7Q7A9zn74KGQe6d55nGH5idp3sTJ/x25h1I86jfUV9dqVmQwbzVnkRKCkzjKJJvJfit/0s0HAQla5x9wAFsQaGGCHU9iNgHaFX0sV25VM9Nrl6ScRckGWbKJabhk7jHg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden-token
      namespace: vaultwarden