apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden-smtp
  namespace: vaultwarden
spec:
  encryptedData:
    smtp-password: AgCh1pIqa643htoNBhgmnRzcaWBxSR8wiKZQ6+/LkTWiIiipWNZsyEuKl4e1Gtl8eHuvGiguh5hR7mo2cWeI5WtZPRc0Gz2YIakc1kcD6V1cDEpNt1+CRg/VvYkNM7mLme1MQxAGbB14BCKNxR/xcJ4eWTsEPUuNkd0O47UXWEsDutW98ZHbM32G9qFA08tFaSB4Mfjb0G76wrbmjScmJmuOEf6GmQSi6ITH+rUpMc9mnIK6N1UqTt+jKJvdtLoStWxaNrq95L+1sYvADCZwNbQuLSiCPPuhjm9yU0q1q+muJzOTNfnmCiuhDiVpGV9LVdiKUwAzTWUzAUlBf8nf8JvbvqUsZx5QYuk4gPJ/j8/t0shjNKmpQZmdO1mrPecNwM8gWJbciLJSCCNtzldQc9PQ6/w1Fa59DXoYilp6gYWqoFUoXQp3ryFPg0uEcPkEZZYwUwO6cSCv1Oz+lP6rNZebJoOCoxFDpdnBC8NRRNYvCZsRespBWX9nAX4DrGoJDllFFi0rVlPj83iY38BK+AoPd1ZAx642vMnNELclKiO7KBnF8KEn8s5w/I3hsVVev6Yjk1fOJJ+R66P2pb37vHUeVXPgFr4Gsi6g6zptnlzknjw3fvYmWASQZ91kUy/jiKwyk/2CkSw9fplHnBfxrWAG3KgPE91femKc24jg8OtqEqeSct+6Y68CdHhD0Vy+oVXzVLNnAREqd/4H
    smtp-user: AgCtnsuhNssI95LC5+G562PRtfgCrV0GPZ+m9sb0uX0EhXKejA5sQ1nGQK8gV2T+PdjpMpB5wU9aTYJs3w5jQz0hG1P5xMteMjIn3j12z+ezTF6KslY+o0kRe3jHuXHEd9SnWBtF1iNXWGc7+loqxUbONgZFgZbjb366LNsa8f2qeico+NRKYcJWgFBiimwPAh/tELw+/fA8b0+9gvrLI/EIP5wOKm/pY7sHIYCb2qZrzqvV+XM6U1XmWg3LUot2UWak0UjGzSt52DCj+bJvzFqUjXR1woysayP6vY5mk9oHQobuTH+CmqQJSfrJOYRSCi+ymkuxorLtGUkzUx413FxhPYut0+t5+uACJpbNA3g+RXzmiGlh+aXAnn7TXKUDocxP1WbWhOPQT5QIajy3CXHAhf7ujJDQj1G7fpp2gTLZM9Ps7FKllWGlI1DijoQp/7BRGsJ05mZSEbyDa3yP43HQRe0ZcQuJth5PifQNL+o15wyRJNB3bJFNBWhSBAyuQyRYN0K69M+EH5ApxR5rHXZsaBhfOU/6eGCKKIl2i3Ka3qD9tXbrSfTZI7KTumyT9MjgPZNUFVE5JJ3s9+mAisl6qnW/1SvYlU8Shl0/aat2rWcjLoA4G3jid12BgRQ+qxByuDpCnLz9sGd9Nh11LBEoVlTU438EQEnBriomZM+NZpHM+EM5Ej+/1amyiAU1roVDEDMGvqKm6jBEHzXrMRFGcdsgJQc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden-smtp
      namespace: vaultwarden