apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAqOoaWcl3T6OwXWbT4Z8em41lVCoD2VhWjk6f3yO0StOnDACDfvwa8vT+1Klfxq17aHrKKo1mCG44GLSMRl3RivJJiJ6NYdqaTswB7zeft2puKHoMtFAkjQNjuSHy22tprW7FcohIoiXA6n08jhWMnpYMU6J4PTi/+0JJJntVSkqQebjp1VkymeGbfewwWQjlyejB8DBZbEmXUXH44Xv7VtRpmqqTSHDHTMKlkX5u9iSBLXZSOLQ4VkfW4Qs8dg8idlTA6zICXhM7inoxtsGe7k5NnrreJDmipQ/npQJzavXCV7SgsW5NsSwJdQwDh5h94K05WqnFHo8yOD0/N1Q04OTJn3zrw4lqB4jJ/trV/BDRkBI2khgn9Aq78WbM0cLpRlqZJylCYlI4crz9XKcegp3tnEel8KxU2kBVtrtqKobb/S6p3OOPKBkErirM+Iuuuy8uPUlWj0Ta4EwzVBDzoRYvWViakVUhzrQQyR3onBqIRTn9CPU9M3UwmjD68ABbn9EE1nHqreGdwsRn59gxgywEj1437/Zwy/M3d1lAK1LoLWJnQcNGRmGGZjEuAfK2wKNSlaU430e3+8Dw66fOuwzK0difK0MyIFDajL3s2k2ApQrVOF+w7BQ7WKOu05YEe/2jatD2l6cUBou4IudRrIKZ9f0R56FHBPpGufO7r+LusdxKy750nK1T/DjVteozJ5Yl1Zc7Vm7s/yAAiZEM=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden-token
      namespace: vaultwarden
