apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgCoZVDoK3z+fR7sXshXryYpvpYUdT/Abx96rrKErh5SUy0fD8cjBWrbz7Qxh333uu2hMVikiC5V+g1qumW7OPRIk0Wij0qwtWe57XN0T6ttdvS0kxS/P3L3BNqplsTzqmJjiY2hzAb/0si/hDgTuhKU5r4nalmO6zOWVW9UUgN8kN4V9M/1NXgIhTyRiMmnz0cLuBrQMPz/hLxsmw/fQn3zkhXvcQzGDAqc2t1jbuvrrNrd2p4LqvuSQsXx0JO7fuWs/FzaMZLXdwE0TTSSmmD7RFafjRY1ZXfFNAvLuKHmbWj2lS1YntJgBb3co+fzoB6KNCHkQS/W3gUOwc4W1rQP+JBRa5r3d8pSdKwcKCenXVH5Ndh0K0LdTLUzxB9niD7MqKiAp1/ZClENXx3wMKu6AjMBhp55EmL3Pn4zBUvbkgda1CPpTpl+odWIAx00jZ5/uBGqiQOFNXeZ4y+T9wxAI+STp8fTxMrjX7cUpyk0dz4NY7WIop4Dh7lb//JTDs7J/dL9S97V7tcACGAeb7ekE1f0uuoDi94Y3l0kBlsTHWjjz0qGw0dknHPcpJ31tCPch6BQ139coUNCw70vYsYMHOZyohslcIQz7p8fKvj60VLjnWojJNAxnARspElt7TwQDs7ChmQqkQwElktUomF87yRpp1Rld4Q8gmBgak6Fes6hinbLtIGf4iVyOcWZz1JVVArGD5oOLONdhUQGrCA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: admin-token
      namespace: vaultwarden
