apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert-kappes.space
  namespace: letsencrypt-certificates
spec:
  secretName: letsencrypt-wildcard-cert-kappes.space
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
  dnsNames:
  - "kappes.space"
  - "*.kappes.space"