apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCzYVurf1Y0hopWBqCGNA7Yp7q/sIpY0yhfpbY+NCh457quywA8/c9CMWUP2wMRbgkUyRSVhjg3ULNES1ooCpJJsuTPtUxAJJp0/za1UuIJF9nvN3So5N3V01FRbmNsoIIZpL4gi9R1djXet5G402+NXs4xfEKr9dthfP/v7Zh9ud8R6fhYK36c9J2dv/gyF/kvfXgY6NbXj8vJxX/L9YiGbEPvUQ9Fbzbr/Y4zxsiNdylSKxv/OhGDsCon+6QPq/D0sNXCT99PSmJKP3ksyWU/hntMIBvDddXK/zSqPzkc75dVbVbc4HEwpgfG6nF9WO+q+czW3wIiv9kF/nliZXbq7pAlh2UjgO3lE3hzF9XONzttLfaNhJ9mbLKD+jW20NBYhG7IdST7DVmo31Thagbw+FmbmW4J/3fvBhpBuyC4+XuVueCDpT0V2hh+EoGZYCuZlJCj4DFB4ptO1eWHl3Yvk0OPMsp0PAjOQyFopn2D4ydHZ+1vR1u4QA0pNGE2/CVMUZ92JCB5qxCVGoVLBPUEIfT/rI2KsMIUkmFKntIOqc1IXk7SFOOeSfiyM1hNB2cVdAuKF7AE9CH+bVGXft+HGe8N8jjVy/oPvBW/dBncElqYy/NWSc7NEOb/+WEfIrY7APT8gFUiOsaTO/UmYi6nc3X4ma/c6zd9IwoGMOdyc0diezUax8ONfqDt6uWlFGi+kyxGzJNUh+htKHL09LJl2SYIA8gnK5qRDRA1Kn7ozlfMAfbj4boY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager