apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reverse-proxy
  namespace: reverse-proxy
spec:
  chart:
    spec:
      chart: nginx
      version: 15.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: reverse-proxy
  valuesFrom:
  - kind: ConfigMap
    name: configmap-nginx-helm-chart-values-override
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity