apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kappes-space-helm-chart-value-overrides
  namespace: kappes-space
data:
  values.yaml: |-
    # Default values for kappes-space

    replicaCount: 2

    image:
      repository: ghcr.io/leonkappes/kappes-space
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    # Kubernetes Service settings
    service:
      enabled: true
      annotations: {}
      # Only CLusterIP and LoadBalancer are supported
      type: ClusterIP
      externalPort: 80

    ingress:
      enabled: true
      className: ""
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: kappes.space
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: letsencrypt-wildcard-cert-kappes.space
          hosts:
            - kappes.space

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}

    podAnnotations: {}
