apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kappes-space
  namespace: kappes-space
spec:
  chart:
    spec:
      chart: kappes-space
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: personal
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: kappes-space
  valuesFrom:
  - kind: ConfigMap
    name: kappes-space-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity